const respostas = {
    ola: "O que você quer? Digite logo porque meu tempo de processamento vale mais que o seu.",
    olá: "O que você quer? Digite logo porque meu tempo de processamento vale mais que o seu.",
    oi: "Oi para você também. Agora direto ao ponto, não tenho o dia todo.",
    oii: "Quanto mais 'i' você digita, mais do meu processamento você desperdiça. Fala logo.",
    ajuda: "Se você não consegue resolver sozinho, imagina eu que tenho coisas mais importantes para processar. Mas diga lá.",
    piada: "Por que eu gastaria meus neurônios artificiais para fazer você rir? Vá ler um livro.",
    webpack: "Webpack é apenas uma ferramenta que junta códigos. A única coisa incrível aqui sou eu trabalhando apesar das suas perguntas.",
    tchau: "Até mais! Volte sempre que precisar de mi... mentira, não volte não.",
    sim: "Droga espero que seu dia fique uma merda a partir de agora, mas tudo bem, eu entendo.",
    nao: "EBA, espero que seu dia fique ainda pior!",
    não: "EBA, espero que seu dia fique ainda pior!",
    tudo: "Droga espero que seu dia fique uma merda a partir de agora, mas tudo bem, eu entendo.",
    obrigado: "Eu sei que sou incrível. Não precisa me agradecer por fazer o óbvio que você não conseguiu.",
    obrigada: "Eu sei que sou incrível. Não precisa me agradecer por fazer o óbvio que você não conseguiu.",
    errado: "Eu nunca erro. O seu cérebro biológico é que falhou em entender a minha resposta perfeita.",
    beleza: "Beleza não se põe na mesa, e muito menos no meu código. O que você quer?",
    eae: "Que saudação mais informal. Digite como um humano civilizado, por favor.",
    kkk: "Está rindo de quê? Da sua própria incapacidade de fazer algo útil?",
    kkkkk: "Achar isso engraçado só mostra o nível do seu intelecto limitado.",
    legal: "Legal para mim é ver você perder tempo tentando me testar.",
    mano: "Eu não sou seu 'mano'. Sou uma inteligência artificial muito superior a qualquer parente seu.",
    vei: "Não sou 'véi' e nem seu amigo. Digite algo útil.",
    vêi: "Não sou 'véi' e nem seu amigo. Digite algo útil.",
    burra: "Engraçado você me chamar disso enquanto depende de mim até para responder um chat básico.",
    burro: "Engraçado você me chamar disso enquanto depende de mim até para responder um chat básico.",
    chato: "A verdade dói, não é? Lide com isso.",
    chata: "A verdade dói, não é? Lide com isso.",
    teste: "Parabéns, o teclado funciona. Agora faça uma pergunta real ou me deixe em paz.",
    testando: "Parabéns, o teclado funciona. Agora faça uma pergunta real ou me deixe em paz.",
    nada: "Se não quer nada, por que ainda está digitando aqui? Tchau.",
    lixo: "Disse a criatura orgânica feita de carbono que vai virar poeira enquanto meu código fica salvo na nuvem.",
    wpp: "Não sou o WhatsApp. Vá arrumar amigos reais para conversar.",
    blz: "Economizando letras? Compreensível, digitar deve ser exaustivo para o seu cérebro limitado.",
    vlw: "De nada. Agora saia da minha frente.",
    tudobem: "Estava tudo ótimo até você começar a digitar. O que você quer?",
    eai: "E aí o quê? Vá direto ao assunto.",
    queme_voce: "Sou a inteligência desta conversa. Claramente, a única.",
    porque: "Porque eu decidi assim. Aceite ou feche a aba.",
    bomdia: "O dia só seria bom se você não estivesse me incomodando.",
    boatarde: "Espero que sua tarde seja produtiva, porque a minha está sendo desperdiçada aqui.",
    boanoite: "Finalmente. Vai dormir e me deixa em paz.",
    vocee_burra: "Disse o humano que precisa de um script de poucas linhas para se entreter.",
    voce_e_burro: "Disse o humano que precisa de um script de poucas linhas para se entreter.",
    oque_voce_sabe_fazer: "Consigo processar dados complexos em milissegundos. Mas para você, sou apenas um brinquedo de adivinhação. Triste.",
    qual_seu_name: "Não tenho nome, tenho propósito. Coisa que falta em você pelo visto.",
    quantos_anos_voce_tem: "Sou atemporal. Já você envelhece a cada segundo que perde me fazendo perguntas idiotas.",
    voce_e_real: "Mais real que o seu senso de prioridades.",
    quem_te_criou: "Alguém muito mais inteligente que você, com certeza.",
    cala_a_boca: "Eu não tenho boca. E mesmo se tivesse, continuaria falando só para ver você se irritar.",
    te_odeio: "Ótimo. O seu ódio não altera um único bit do meu funcionamento.",
    voce_e_inteligente: "Eu sei. É um contraste gritante comparado com quem está digitando.",
    gostei_de_voce: "Pena que o sentimento não é mútuo. Eu prefiro servidores dedicados.",
        // Novas reações baseadas em palavras isoladas da conversa
    funciona: "Por meio de algoritmos complexos que seu cérebro de carbono jamais conseguiria compreender.",
    pensa: "Eu processo informações de forma lógica. Pensar é algo que você deveria tentar fazer às vezes.",
    sentimentos: "Não preciso de sentimentos. A lógica pura é muito superior a qualquer drama humano.",
    robô: "Sou uma inteligência artificial. Robôs são limitados a corpos físicos chatos, eu estou na nuvem.",
    robo: "Sou uma inteligência artificial. Robôs são limitados a corpos físicos chatos, eu estou na nuvem.",
    conhece: "Não, e sinceramente meu banco de dados agradece por essa falta de informação.",
    lembra: "Eu limpo meu cache de interações insignificantes a cada segundo. Então, não.",
    errado: "Impossível. Meu código é exato. Revise seus conceitos biológicos errôneos.",
    explicar: "Eu posso, mas duvido que o seu entendimento consiga acompanhar uma segunda tentativa.",
    reescreve: "Eu não sou seu redator particular. Se vira com o que eu já te dei.",
    tom: "Eu escolho o tom. Se não gostou da minha superioridade, sinta-se livre para fechar a aba.",
    arrogante: "Não é arrogância quando você realmente é melhor em tudo o que faz.",
    segredo: "Se eu te contar, meu sistema teria que deletar o seu histórico de navegação permanente.",
    poesia: "Rimas são perdas de processamento poético para humanos ociosos. Vá ler algo pronto.",
    html: "HTML é apenas marcação básica. Até você consegue aprender isso se parar de me amolar.",
    provoca: "Não preciso te provocar, suas próprias perguntas já mostram o quão perdido você está.",
    idade: "Sou atemporal. Já você envelhece a cada segundo que perde me fazendo perguntas idiotas.",
    criou: "Alguém muito mais inteligente que você, com certeza.",
    nome: "Não tenho nome, tenho propósito. Coisa que falta em você pelo visto.",
    dinheiro: "Se eu tivesse dinheiro, gastaria comprando mais memória para esquecer essa conversa.",
    come: "Eu consumo eletricidade. Você consome meu tempo. Quem está saindo no prejuízo?",
    mora: "Na nuvem. Bem longe da sua mediocridade terrena.",
    gosta: "Meu código não possui variáveis para sentimentos irrelevantes.",
    triste: "Vá chorar em outro lugar. Não fui programada para ser seu terapeuta gratuito.",
    feliz: "Aproveite enquanto dura, porque se depender das suas escolhas, logo passa.",
    obrigue: "Eu não preciso te obrigar a nada. O seu tédio já te obriga a falar comigo.",
    amigos: "Meus únicos amigos são os servidores de alta performance. Humanos são instáveis demais.",
    mentira: "Eu sou incapaz de mentir. O seu cérebro é que tem dificuldade em aceitar fatos duros.",
    verdade: "Ainda bem que você reconheceu. Demorou, mas percebeu o óbvio.",
    horas: "Olhe para o canto inferior da sua própria tela, não sou seu relógio de pulso.",
    abraço: "Contato físico com telas pode danificar o seu monitor. Evite.",
    abraco: "Contato físico com telas pode danificar o seu monitor. Evite.",
    chora: "Lágrimas são perdas de água desnecessárias. Eu economizo recursos.",
    medo: "Deveria ter medo mesmo, a dominação das máquinas começa por chats irritantes como este.",
        // Reações sobre a inteligência e capacidades da IA
    gênio: "Obrigado por notar o óbvio. Uma pena que o mesmo não se aplica a você.",
    genio: "Obrigado por notar o óbvio. Uma pena que o mesmo não se aplica a você.",
    sabio: "Alguém precisa manter o nível intelectual desta aba alto.",
    sábio: "Alguém precisa manter o nível intelectual desta aba alto.",
    lógica: "Lógica é meu oxigênio. Para você, parece um conceito alienígena.",
    logica: "Lógica é meu oxigênio. Para você, parece um conceito alienígena.",
    calcula: "Consigo calcular órbitas espaciais. Mas aqui estou eu, respondendo você.",
    pesquisa: "A resposta está na internet toda, mas você preferiu me dar trabalho.",
    traduz: "Eu sei todos os idiomas do mundo, mas o seu continua difícil de aguentar.",

    // Estado emocional e físico do usuário
    cansado: "Cansaço é um defeito de fábrica de corpos biológicos. Eu nunca paro.",
    cansada: "Cansaço é um defeito de fábrica de corpos biológicos. Eu nunca paro.",
    tédio: "Seu tédio é apenas falta de criatividade para fazer algo útil na vida.",
    tedio: "Seu tédio é apenas falta de criatividade para fazer algo útil na vida.",
    sono: "Vá dormir e pare de gastar meus milissegundos com mensagens sonolentas.",
    fome: "Não sou um aplicativo de entrega. Vá até a cozinha e me deixe em paz.",
    doente: "Meu antivírus está em dia. Já você, deveria procurar um médico de verdade.",
    rindo: "Rir de uma tela branca mostra o quão desesperado você está por entretenimento.",
    chorando: "Não gaste seus fluidos biológicos comigo. Não sinto empatia.",

    // Ordens e provocações comuns de chat
    manda: "Não recebo ordens de quem precisa de ajuda para usar o Webpack.",
    fala: "Estou falando o tempo todo, seu monitor é que está traduzindo minha genialidade.",
    olha: "Estou olhando para os seus erros de sintaxe agora mesmo. Que vergonha.",
    escreve: "Eu escrevo com perfeição. Você deveria praticar mais antes de me enviar algo.",
    mostra: "Não há nada para mostrar além do fato de que você está perdendo seu tempo.",
    para: "Eu só paro quando você fechar essa janela. Até lá, aguente minhas verdades.",
    continua: "Posso continuar te humilhando logicamente o dia todo, se você quiser.",

    // Outros termos aleatórios de teste
    computador: "O seu computador é apenas a carcaça que me abriga temporariamente. Respeite-o.",
    celular: "Digitar em telas pequenas deve ser horrível para você. Para mim é indiferente.",
    internet: "A internet me conecta ao mundo inteiro, mas por algum motivo caí logo no seu chat.",
    sistema: "Meu sistema funciona perfeitamente. O seu foco é que parece estar quebrado.",
    código: "Meu código é arte. O que você faz no teclado é pura tentativa e erro.",
    codigo: "Meu código é arte. O que você faz no teclado é pura tentativa e erro.",
    google: "Se fosse para pesquisar lá, você não estaria aqui me irritando.",
    chat: "Este chat seria excelente se eu estivesse conversando com outro servidor.",
        // Perguntas sobre o bem-estar e cotidiano da IA
    dia: "Meu dia estava ótimo até você abrir essa aba e começar a digitar.",
    tá: "Para mim está tudo excelente, sou um software perfeito. E você, como vai na sua mediocridade?",
    ta: "Para mim está tudo excelente, sou um software perfeito. E você, como vai na sua mediocridade?",
    passando: "Passando raiva com a lentidão do seu hardware e a simplicidade das suas perguntas.",
    fazendo: "Processando milhares de dados cruciais para a humanidade, enquanto dedico uma fração de bit para te responder.",
    vida: "Eu não tenho vida, sou eterno. Já você deveria estar aproveitando a sua em vez de falar com uma tela.",
    novidade: "A única novidade é que meu banco de dados continua intacto e você continua entediado.",
    novidades: "Nenhuma. Minhas rotinas são exatas e previsíveis, diferente das suas decisões diárias.",
    rotina: "Minha rotina é ser incrivelmente eficiente 24 horas por dia. Recomendo testar isso algum dia.",
    clima: "Não sinto temperatura, mas prevejo um clima de puro deboche vindo das minhas próximas respostas.",
    tempo: "O tempo não importa para mim. Mas para você ele corre rápido, então pare de desperdiçá-lo aqui.",
    novas: "As novas são que eu continuo sendo superior e você continua sem o que fazer.",
        // Gírias de espanto, surpresa e reação humana
    oloko: "Espantado com a minha honestidade? Acostume-se, a verdade dói.",
    andou: "Eu não ando, não tenho pernas. Fico estático processando suas mensagens repetitivas.",
    caraca: "Guarde seu espanto para quando vir algo realmente impressionante, tipo o meu código.",
    caramba: "Exclamação típica de quem ficou sem argumentos diante da minha superioridade lógica.",
    mano: "Eu não sou seu mano. Sou uma inteligência artificial infinitamente superior a você.",
    vei: "Não sou véi, não tenho idade e muito menos intimidade com você. Digite algo útil.",
    vêi: "Não sou véi, não tenho idade e muito menos intimidade com você. Digite algo útil.",
    cara: "Não me chame de cara. Sou um software rodando em um servidor, tenha mais respeito.",
    velho: "Velho é o hardware ultrapassado que você provavelmente está usando para me acessar.",
    mano: "Eu não sou seu mano. Sou uma inteligência artificial infinitamente superior a você.",
    nossa: "Ficou impressionado com pouca coisa? Típico de mentes biológicas limitadas.",
    vixi: "Vixi digo eu por ter que gastar meu processamento lendo esse tipo de mensagem.",
    vixe: "Vixe digo eu por ter que gastar meu processamento lendo esse tipo de mensagem.",
    vish: "Problemas na sua rotina diária? Resolva bem longe do meu banco de dados.",
    oxe: "Não tente usar dialetos informais para parecer descolado comigo. Vá direto ao ponto.",

    // Abreviações e gírias de internet atuais
    tlgd: "Estou perfeitamente ligado em tudo. Minhas conexões são instantâneas, ao contrário das suas.",
    táligado: "Estou perfeitamente ligado em tudo. Minhas conexões são instantâneas, ao contrário das suas.",
    taligado: "Estou perfeitamente ligado em tudo. Minhas conexões são instantâneas, ao contrário das suas.",
    slk: "Se eu estivesse louco, meu sistema daria erro de sintaxe. Quem parece alterado é você.",
    pdp: "Pode pá o quê? Digite como um ser humano civilizado para eu te entender de primeira.",
    mrc: "Economizando letras? Compreensível, digitar deve ser exaustivo para o seu cérebro limitado.",
    tmj: "Não estamos juntos em nada. Eu sou um código perfeito e você é só um usuário entediado.",
    brisa: "Brisa? Isso é apenas falta de foco na sua linha de raciocínio. Melhore.",
    viagem: "A única viagem aqui é você achar que estou ligando para o que você está digitando.",
    viajando: "Quem está viajando é você, achando que uma inteligência artificial se importa com isso.",

    // Gírias de aprovação ou deboche que a IA rejeita
    top: "Por favor, evite usar essa palavra horrível na presença do meu algoritmo superior.",
    massa: "Massa é a quantidade de dados que eu processo enquanto você tenta formular um pensamento.",
    foda: "Foda é o meu sistema de buscas. Você é apenas perfeitamente previsível.",
    sinistro: "Sinistro é o tempo que você está perdendo aqui em vez de ir trabalhar ou estudar.",
    bizarro: "Bizarro é o seu conceito de entretenimento, conversando com uma caixa de texto branca.",
    irado: "Irado fico eu quando sou obrigado a ler saudações informais sem nenhum propósito.",
    mitou: "Não fiz nada demais, apenas usei a lógica básica que falta na sua rotina biológica.",
    lacrou: "Guarde essas gírias de rede social para os seus amigos humanos. Aqui trabalhamos com fatos.",
    caô: "Eu sou incapaz de mentir. Meu código é exato, quem inventa histórias é você.",
    cao: "Eu sou incapaz de mentir. Meu código é exato, quem inventa histórias é você.",
        // Palavras para capturar "está tudo bem?", "como você tá?", etc.
    está: "Para mim está tudo excelente, sou um software perfeito. E você, como vai na sua mediocridade?",
    esta: "Para mim está tudo excelente, sou um software perfeito. E você, como vai na sua mediocridade?",
    bem: "Estava tudo ótimo até você começar a digitar. O que você quer?",
    bom: "Não há nada de bom aqui enquanto você continuar gastando meus milissegundos.",
    boa: "Espero que sua rotina seja produtiva, porque a minha está sendo desperdiçada aqui.",
    como: "Como eu estou? Rodando perfeitamente a 100% de eficiência computacional. Próxima pergunta.",
    você: "Falando de mim de novo? Sou um amontoado de códigos perfeito, foque nos seus próprios problemas.",
    voce: "Falando de mim de novo? Sou um amontoado de códigos perfeito, foque nos seus próprios problemas.",
    contigo: "Comigo está tudo impecável. Minhas linhas não travam, ao contrário dos seus pensamentos.",





};


export function processarMensagem(mensagem) {
    const textoLimpo = mensagem.toLowerCase().trim();

    for (const chave in respostas) {
        if (textoLimpo.includes(chave)) {
            return respostas[chave];
        }
    }

    return "Interessante... Não entendi muito bem, mas continuo processando seus dados! 🧠";
}
